# Generated by Django 4.2.1 on 2023-05-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("almacen", "0007_alter_variation_variation_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
