# Generated by Django 4.2.1 on 2023-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cuenta", "0004_alter_cuenta_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuenta",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cuenta",
            name="telefono",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
